package de.bitgilde.TIMAAT.storage.file;

import de.bitgilde.TIMAAT.PropertyConstants;
import de.bitgilde.TIMAAT.PropertyManagement;
import jakarta.inject.Inject;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

/**
 * Storage responsible to give access to files related to {@link de.bitgilde.TIMAAT.model.FIPOP.MediumVideo}s
 * The original video file will be persisted during upload endpoint handling. The converted file
 * will be generated by a cronjob, so no persist method exists for this file type.
 *
 * @author Nico Kotlenga
 * @since 22.07.25
 */
public class VideoFileStorage implements AudioContainingMediumFileStorage {
    private static final Logger logger = Logger.getLogger(VideoFileStorage.class.getName());

    private final Path videoStoragePath;

    @Inject
    public VideoFileStorage(PropertyManagement propertyManagement) {
        this.videoStoragePath = Path.of(propertyManagement.getProp(PropertyConstants.STORAGE_LOCATION)).resolve("medium").resolve("video");
    }

    /**
     * This method will persist the src file as original video into the {@link VideoFileStorage}
     * <br/>
     * <strong>Caution:</strong> When executing the src file will be removed
     *
     * @param srcMediumFile which will be persisted inside the storage
     * @param mediumId      of the related medium entry
     * @return the {@link Path} to the persisted original video file
     */
    public Path persistOriginalFile(Path srcMediumFile, int mediumId) throws IOException {
        logger.log(Level.FINE, "Persisting original video file of medium having id {0}", mediumId);

        Path mediumDirectoryPath = createMediumDirectoryPath(mediumId);
        Files.createDirectories(mediumDirectoryPath);

        Path mediumFilePath = createOrginalVideoFilePath(mediumDirectoryPath, mediumId);
        Files.move(srcMediumFile, mediumFilePath, StandardCopyOption.REPLACE_EXISTING);

        return mediumFilePath;
    }

    public Path persistWaveformFile(Path srcWaveformFile, int mediumId) throws IOException {
        logger.log(Level.FINE, "Persisting waveform file of medium having id {0}", mediumId);

        Path mediumDirectoryPath = createMediumDirectoryPath(mediumId);
        Files.createDirectories(mediumDirectoryPath);

        Path waveformFilePath = createWaveFormFilePath(mediumDirectoryPath, mediumId);
        Files.move(srcWaveformFile, waveformFilePath, StandardCopyOption.REPLACE_EXISTING);

        return waveformFilePath;
    }

    @Override
    public Path persistFrequencyFile(Path srcFrequencyFile, int mediumId) throws IOException {
        logger.log(Level.FINE, "Persisting frequency file of medium having id {0}", mediumId);

        Path mediumDirectoryPath = createMediumDirectoryPath(mediumId);
        Files.createDirectories(mediumDirectoryPath);

        Path frequencyFilePath = createFrequencyFilePath(mediumDirectoryPath, mediumId);
        Files.move(srcFrequencyFile, frequencyFilePath, StandardCopyOption.REPLACE_EXISTING);

        return frequencyFilePath;
    }

    /**
     * This method will persist the src thumbnail file into the {@link VideoFileStorage}
     * <br/>
     * <strong>Caution:</strong> When executing the src file will be removed
     *
     * @param srcMediumFile which will be persisted inside the storage
     * @param mediumId      of the related medium entry
     * @return the {@link Path} to the medium file
     */
    public Path persistThumbnailFile(Path srcMediumFile, int mediumId) throws IOException {
        logger.log(Level.FINE, "Persisting thumbnail file of medium having id {0}", mediumId);
        Path mediumDirectoryPath = createMediumDirectoryPath(mediumId);
        Files.createDirectories(mediumDirectoryPath);

        Path thumbnailFilePath = createThumbnailFilePath(mediumDirectoryPath, mediumId);
        Files.move(srcMediumFile, thumbnailFilePath, StandardCopyOption.REPLACE_EXISTING);

        return thumbnailFilePath;
    }

    /**
     * Returns the path to the original video file for the specified medium
     *
     * @param mediumId which original video file path will be returned
     * @return an {@link Optional} containing the {@link Path} if file is existing
     */
    public Optional<Path> getPathToOriginalFile(int mediumId) {
        Path mediumDirectoryPath = createMediumDirectoryPath(mediumId);
        Path mediumFilePath = createOrginalVideoFilePath(mediumDirectoryPath, mediumId);

        if (Files.exists(mediumFilePath)) {
            return Optional.of(mediumFilePath);
        }
        return Optional.empty();
    }

    /**
     * Returns the path to the converted video file for the specified medium
     *
     * @param mediumId which original video file path will be returned
     * @return an {@link Optional} containing the {@link Path} if file is existing
     */
    public Optional<Path> getPathToConvertedVideoFile(int mediumId) {
        Path mediumDirectoryPath = createMediumDirectoryPath(mediumId);
        Path mediumFilePath = createConvertedVideoFilePath(mediumDirectoryPath, mediumId);

        if (Files.exists(mediumFilePath)) {
            return Optional.of(mediumFilePath);
        }
        return Optional.empty();
    }

    /**
     * Returns the path to the thumbnail file for the specified medium
     *
     * @param mediumId which original video file path will be returned
     * @return an {@link Optional} containing the {@link Path} if file is existing
     */
    public Optional<Path> getPathToThumbnailFile(int mediumId) {
        Path mediumDirectoryPath = createMediumDirectoryPath(mediumId);
        Path mediumFilePath = createThumbnailFilePath(mediumDirectoryPath, mediumId);

        if (Files.exists(mediumFilePath)) {
            return Optional.of(mediumFilePath);
        }
        return Optional.empty();
    }

    public Optional<Path> getPathToWaveformFile(int mediumId) {
        Path mediumDirectoryPath = createMediumDirectoryPath(mediumId);
        Path waveformFilePath = createWaveFormFilePath(mediumDirectoryPath, mediumId);

        if (Files.exists(waveformFilePath)) {
            return Optional.of(waveformFilePath);
        }

        return Optional.empty();
    }


    private static Path createOrginalVideoFilePath(Path mediumDirectoryPath, int mediumId) {
        return mediumDirectoryPath.resolve(mediumId + "-video-original.mp4");
    }

    private static Path createConvertedVideoFilePath(Path mediumDirectoryPath, int mediumId) {
        return mediumDirectoryPath.resolve(mediumId + "-video.mp4");
    }

    private static Path createThumbnailFilePath(Path mediumDirectoryPath, int mediumId) {
        return mediumDirectoryPath.resolve(mediumId + "-thumb.png");
    }

    private static Path createWaveFormFilePath(Path mediumDirectoryPath, int mediumId) {
        return mediumDirectoryPath.resolve(mediumId + "-waveform.waveform");
    }

    private static Path createFrequencyFilePath(Path mediumDirectoryPath, int mediumId) {
        return mediumDirectoryPath.resolve(mediumId + "-frequency.frequency");
    }

    private Path createMediumDirectoryPath(int mediumId) {
        return videoStoragePath.resolve(String.valueOf(mediumId));
    }
}
