UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Martinez & Scheffel: Unreliable Narration' WHERE `analysis_method_type_translation`.`id` = 1;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Color Temperature' WHERE `analysis_method_type_translation`.`id` = 7;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Position and Perspective' WHERE `analysis_method_type_translation`.`id` = 8;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Elevation' WHERE `analysis_method_type_translation`.`id` = 9;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Axis of Action' WHERE `analysis_method_type_translation`.`id` = 10;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Horizontal Angle' WHERE `analysis_method_type_translation`.`id` = 11;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Vertical Angle' WHERE `analysis_method_type_translation`.`id` = 12;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Shot Type' WHERE `analysis_method_type_translation`.`id` = 13;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Distance' WHERE `analysis_method_type_translation`.`id` = 14;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Movement' WHERE `analysis_method_type_translation`.`id` = 16;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Handling' WHERE `analysis_method_type_translation`.`id` = 17;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Sound Effect Descriptive' WHERE `analysis_method_type_translation`.`id` = 20;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Ambient Sound' WHERE `analysis_method_type_translation`.`id` = 21;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Music' WHERE `analysis_method_type_translation`.`id` = 22;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Speech' WHERE `analysis_method_type_translation`.`id` = 23;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Voice' WHERE `analysis_method_type_translation`.`id` = 24;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Lighting Type' WHERE `analysis_method_type_translation`.`id` = 25;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Montage Figure Macro' WHERE `analysis_method_type_translation`.`id` = 26;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Montage Figure Micro' WHERE `analysis_method_type_translation`.`id` = 27;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Take Junctions' WHERE `analysis_method_type_translation`.`id` = 28;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Editing Rhythm' WHERE `analysis_method_type_translation`.`id` = 29;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Take Length' WHERE `analysis_method_type_translation`.`id` = 30;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Take Type Progression' WHERE `analysis_method_type_translation`.`id` = 31;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Playback Speed' WHERE `analysis_method_type_translation`.`id` = 32;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Image Cadre Editing' WHERE `analysis_method_type_translation`.`id` = 33;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Editing and Montage' WHERE `analysis_method_type_translation`.`id` = 34;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Direction' WHERE `analysis_method_type_translation`.`id` = 35;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Movement Characteristic' WHERE `analysis_method_type_translation`.`id` = 36;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Camera Movement Type' WHERE `analysis_method_type_translation`.`id` = 37;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Light Position: General' WHERE `analysis_method_type_translation`.`id` = 38;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Light Position Angle Horizontal' WHERE `analysis_method_type_translation`.`id` = 39;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Light Position Angle Vertical' WHERE `analysis_method_type_translation`.`id` = 40;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Light Modifier' WHERE `analysis_method_type_translation`.`id` = 41;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Lighting Duration' WHERE `analysis_method_type_translation`.`id` = 42;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Actor' WHERE `analysis_method_type_translation`.`id` = 44;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Acting Technique' WHERE `analysis_method_type_translation`.`id` = 45;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Facial Expression' WHERE `analysis_method_type_translation`.`id` = 46;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Facial Expression Intensity' WHERE `analysis_method_type_translation`.`id` = 47;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Physical Expression' WHERE `analysis_method_type_translation`.`id` = 48;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Physical Expression Intensity' WHERE `analysis_method_type_translation`.`id` = 49;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Gestural Emotion' WHERE `analysis_method_type_translation`.`id` = 50;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Gestural Emotion Intensity' WHERE `analysis_method_type_translation`.`id` = 51;
UPDATE `FIPOP`.`analysis_method_type_translation` SET `name` = 'Depth of Focus' WHERE `analysis_method_type_translation`.`id` = 52;
