SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `FIPOP`.`medium_audio` CHANGE `audio_codec_information_id` `audio_codec_information_id` INT(11) NULL;
ALTER TABLE `medium_audio` DROP FOREIGN KEY `fk_medium_audio_audio_post_production1`;
ALTER TABLE `medium_audio` ADD CONSTRAINT `fk_medium_audio_audio_post_production1` FOREIGN KEY (`audio_codec_information_id`) REFERENCES `audio_codec_information`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION;

DROP TABLE `FIPOP`.`hashtag`;
DROP TABLE `FIPOP`.`image_gallery_has_medium_image`;
DROP TABLE `FIPOP`.`sioc_container`;
DROP TABLE `FIPOP`.`sioc_container_access_type`;
DROP TABLE `FIPOP`.`sioc_container_access_type_translation`;
DROP TABLE `FIPOP`.`sioc_container_has_role_in_area`;
DROP TABLE `FIPOP`.`sioc_container_has_sioc_user_account`;
DROP TABLE `FIPOP`.`sioc_container_permission_area`;
DROP TABLE `FIPOP`.`sioc_container_permission_area_translation`;
DROP TABLE `FIPOP`.`sioc_container_type`;
DROP TABLE `FIPOP`.`sioc_container_type_translation`;
DROP TABLE `FIPOP`.`sioc_item`;
DROP TABLE `FIPOP`.`sioc_item_has_attached_medium`;
DROP TABLE `FIPOP`.`sioc_item_has_hashtag`;
DROP TABLE `FIPOP`.`sioc_item_has_sioc_item_posting_type`;
DROP TABLE `FIPOP`.`sioc_item_has_sioc_reaction`;
DROP TABLE `FIPOP`.`image_gallery`;
DROP TABLE `FIPOP`.`sioc_item_mentions_sioc_user_account`;
DROP TABLE `FIPOP`.`sioc_item_posting_type`;
DROP TABLE `FIPOP`.`sioc_item_posting_type_translation`;
DROP TABLE `FIPOP`.`sioc_reaction`;
DROP TABLE `FIPOP`.`sioc_reaction_translation`;
DROP TABLE `FIPOP`.`sioc_site`;
DROP TABLE `FIPOP`.`sioc_site_has_sioc_user_account`;
DROP TABLE `FIPOP`.`sioc_site_type`;
DROP TABLE `FIPOP`.`sioc_site_type_translation`;
DROP TABLE `FIPOP`.`sioc_user_account`;
DROP TABLE `FIPOP`.`sioc_user_account_follows_sioc_user_account`;
DROP TABLE `FIPOP`.`sioc_user_account_privacy_setting`;
DROP TABLE `FIPOP`.`sioc_user_account_privacy_setting_translation`;
DROP TABLE `FIPOP`.`sioc_user_account_subscribes_to_video_gallery`;
DROP TABLE `FIPOP`.`video_gallery`;
DROP TABLE `FIPOP`.`video_gallery_has_medium_video`;

SET FOREIGN_KEY_CHECKS=1;