ALTER TABLE `FIPOP`.`category_set_has_category` DROP FOREIGN KEY `fk_category_set_has_category_category_set1`; 
ALTER TABLE `FIPOP`.`category_set_has_category` ADD CONSTRAINT `fk_category_set_has_category_category_set1` FOREIGN KEY (`category_set_id`) REFERENCES `FIPOP`.`category_set` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION; 
ALTER TABLE `FIPOP`.`category_set_has_category` DROP FOREIGN KEY `fk_category_set_has_category_category1`; 
ALTER TABLE `FIPOP`.`category_set_has_category` ADD CONSTRAINT `fk_category_set_has_category_category1` FOREIGN KEY (`category_id`) REFERENCES `FIPOP`.`category` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION; 
ALTER TABLE `FIPOP`.`actor_has_role` DROP FOREIGN KEY `fk_actor_has_role_actor1`; 
ALTER TABLE `FIPOP`.`actor_has_role` ADD CONSTRAINT `fk_actor_has_role_actor1` FOREIGN KEY (`actor_id`) REFERENCES `actor`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION; 
ALTER TABLE `FIPOP`.`actor_has_role` DROP FOREIGN KEY `fk_actor_has_role_role1`; 
ALTER TABLE `FIPOP`.`actor_has_role` ADD CONSTRAINT `fk_actor_has_role_role1` FOREIGN KEY (`role_id`) REFERENCES `role`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`medium_has_actor_with_role` DROP FOREIGN KEY `fk_medium_has_actor_with_role_actor_has_role1`; 
ALTER TABLE `FIPOP`.`medium_has_actor_with_role` ADD CONSTRAINT `fk_medium_has_actor_with_role_actor_has_role1` FOREIGN KEY (`actor_has_role_actor_id`, `actor_has_role_role_id`) REFERENCES `actor_has_role`(`actor_id`, `role_id`) ON DELETE CASCADE ON UPDATE NO ACTION; 
ALTER TABLE `FIPOP`.`medium_has_actor_with_role` DROP FOREIGN KEY `fk_medium_has_actor_with_role_medium1`; 
ALTER TABLE `FIPOP`.`medium_has_actor_with_role` ADD CONSTRAINT `fk_medium_has_actor_with_role_medium1` FOREIGN KEY (`medium_id`) REFERENCES `medium`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;