ALTER TABLE `FIPOP`.`analysis` DROP FOREIGN KEY IF EXISTS `fk_analysis_annotation1`;
ALTER TABLE `FIPOP`.`analysis` DROP FOREIGN KEY IF EXISTS `fk_analysis_analysis_method1`;
ALTER TABLE `FIPOP`.`analysis_ambient_sound` DROP FOREIGN KEY IF EXISTS `fk_analysis_ambient_sound_analysis_method1`;
ALTER TABLE `FIPOP`.`analysis_method_has_religious_reference` DROP FOREIGN KEY IF EXISTS `fk_analysis_method_has_religious_reference_analysis_method1`;
ALTER TABLE `FIPOP`.`analysis_music` DROP FOREIGN KEY IF EXISTS `fk_analysis_music_analysis_method1`;
ALTER TABLE `FIPOP`.`analysis_speech` DROP FOREIGN KEY IF EXISTS `fk_analysis_speech_analysis_method1`;
ALTER TABLE `FIPOP`.`analysis_voice` DROP FOREIGN KEY IF EXISTS `fk_analysis_voice_analysis_method1`;
ALTER TABLE `FIPOP`.`barthes_rhetoric_of_the_image` DROP FOREIGN KEY IF EXISTS `fk_barthes_rhetoric_of_the_image_analysis_method1`;
ALTER TABLE `FIPOP`.`camera_axis_of_action` DROP FOREIGN KEY IF EXISTS `fk_camera_axis_of_action_analysis_method1`;
ALTER TABLE `FIPOP`.`camera_distance` DROP FOREIGN KEY IF EXISTS `fk_camera_distance_analysis_method1`;
ALTER TABLE `FIPOP`.`camera_elevation` DROP FOREIGN KEY IF EXISTS `fk_camera_elevation_analysis_method1`;
ALTER TABLE `FIPOP`.`camera_handling` DROP FOREIGN KEY IF EXISTS `fk_camera_handling_analysis_method1`;
ALTER TABLE `FIPOP`.`camera_horizontal_angle` DROP FOREIGN KEY IF EXISTS `fk_camera_horizontal_angle_analysis_method1`;
ALTER TABLE `FIPOP`.`camera_movement` DROP FOREIGN KEY IF EXISTS `fk_camera_movement_analysis_method1`;
ALTER TABLE `FIPOP`.`camera_shot_type` DROP FOREIGN KEY IF EXISTS `fk_camera_shot_type_analysis_method1`;
ALTER TABLE `FIPOP`.`camera_vertical_angle` DROP FOREIGN KEY IF EXISTS `fk_camera_vertical_angle_analysis_method1`;
ALTER TABLE `FIPOP`.`color_temperature` DROP FOREIGN KEY IF EXISTS `fk_color_temperature_analysis_method1`;
ALTER TABLE `FIPOP`.`color_temperature` DROP FOREIGN KEY IF EXISTS `fk_camera_elevation_analysis_method1`;
ALTER TABLE `FIPOP`.`color_temperature` DROP FOREIGN KEY IF EXISTS `fk_camera_elevation_analysis_method10`;
ALTER TABLE `FIPOP`.`concept_camera_movement_and_handling` DROP FOREIGN KEY IF EXISTS `fk_concept_camera_movement_and_handling_analysis_method1`;
ALTER TABLE `FIPOP`.`concept_camera_position_and_perspective` DROP FOREIGN KEY IF EXISTS `fk_concept_camera_position_and_perspective_analysis_method1`;
ALTER TABLE `FIPOP`.`connoted_image` DROP FOREIGN KEY IF EXISTS `fk_connoted_image_barthes_rhetoric_of_the_image1`;
ALTER TABLE `FIPOP`.`denoted_image` DROP FOREIGN KEY IF EXISTS `fk_denoted_image_barthes_rhetoric_of_the_image1`;
ALTER TABLE `FIPOP`.`genette_narrative_discourse` DROP FOREIGN KEY IF EXISTS `fk_genette_narrative_discourse_analysis_method1`;
ALTER TABLE `FIPOP`.`greimas_actantial_model` DROP FOREIGN KEY IF EXISTS `fk_greimas_actantial_model_analysis_method1`;
ALTER TABLE `FIPOP`.`greimas_actantial_model_has_actor` DROP FOREIGN KEY IF EXISTS `fk_greimas_actantial_model_has_actor_greimas_actantial_model1`;
ALTER TABLE `FIPOP`.`greimas_actantial_model_has_concept` DROP FOREIGN KEY IF EXISTS `fk_greimas_actantial_model_has_concept_greimas_actantial_model1`;
ALTER TABLE `FIPOP`.`linguistic_message` DROP FOREIGN KEY IF EXISTS `fk_linguistic_message_barthes_rhetoric_of_the_image1`;
ALTER TABLE `FIPOP`.`lotman_renner_spatial_semantics` DROP FOREIGN KEY IF EXISTS `fk_lotman_renner_spatial_semantics_analysis_method1`;
ALTER TABLE `FIPOP`.`martinez_scheffel_unreliable_narration` DROP FOREIGN KEY IF EXISTS `fk_martinez_scheffel_unreliable_narration_analysis_method1`;
ALTER TABLE `FIPOP`.`sound_effect_descriptive` DROP FOREIGN KEY IF EXISTS `fk_sound_effect_descriptive_analysis_method1`;
ALTER TABLE `FIPOP`.`spatial_semantics_type_actor_person` DROP FOREIGN KEY IF EXISTS `fk_spatial_semantics_type_actor_person_lotman_renner_spatial_s1`;
ALTER TABLE `FIPOP`.`spatial_semantics_type_space` DROP FOREIGN KEY IF EXISTS `fk_spatial_semantics_type_space_lotman_renner_spatial_semantics1`;
ALTER TABLE `FIPOP`.`stanzel_narrative_situations` DROP FOREIGN KEY IF EXISTS `fk_stanzel_narrative_situations_analysis_method1`;
ALTER TABLE `FIPOP`.`van_sijll_cinematic_storytelling` DROP FOREIGN KEY IF EXISTS `fk_van_sijll_cinematic_storytelling_analysis_method1`;
ALTER TABLE `FIPOP`.`zelizer_beese_voice_of_the_visual` DROP FOREIGN KEY IF EXISTS `fk_zelizer_beese_voice_of_the_visual_analysis_method1`;

ALTER TABLE `FIPOP`.`analysis_method` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT; 

ALTER TABLE `FIPOP`.`analysis` ADD CONSTRAINT `fk_analysis_annotation1` FOREIGN KEY (`annotation_id`) REFERENCES `FIPOP`.`annotation` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`analysis` ADD CONSTRAINT `fk_analysis_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`analysis_ambient_sound` ADD CONSTRAINT `fk_analysis_ambient_sound_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`analysis_method_has_religious_reference` ADD CONSTRAINT `fk_analysis_method_has_religious_reference_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`analysis_music` ADD CONSTRAINT `fk_analysis_music_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`analysis_speech` ADD CONSTRAINT `fk_analysis_speech_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`analysis_voice` ADD CONSTRAINT `fk_analysis_voice_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`barthes_rhetoric_of_the_image` ADD CONSTRAINT `fk_barthes_rhetoric_of_the_image_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`camera_axis_of_action` ADD CONSTRAINT `fk_camera_axis_of_action_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`camera_distance` ADD CONSTRAINT `fk_camera_distance_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`camera_elevation` ADD CONSTRAINT `fk_camera_elevation_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`camera_handling` ADD CONSTRAINT `fk_camera_handling_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`camera_horizontal_angle` ADD CONSTRAINT `fk_camera_horizontal_angle_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`camera_movement` ADD CONSTRAINT `fk_camera_movement_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`camera_shot_type` ADD CONSTRAINT `fk_camera_shot_type_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`camera_vertical_angle` ADD CONSTRAINT `fk_camera_vertical_angle_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`color_temperature` ADD CONSTRAINT `fk_color_temperature_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`concept_camera_movement_and_handling` ADD CONSTRAINT `fk_concept_camera_movement_and_handling_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`concept_camera_position_and_perspective` ADD CONSTRAINT `fk_concept_camera_position_and_perspective_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`connoted_image` ADD CONSTRAINT `fk_connoted_image_barthes_rhetoric_of_the_image1` FOREIGN KEY (`barthes_rhetoric_of_the_image_analysis_method_id`) REFERENCES `FIPOP`.`barthes_rhetoric_of_the_image` (`analysis_method_id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`denoted_image` ADD CONSTRAINT `fk_denoted_image_barthes_rhetoric_of_the_image1` FOREIGN KEY (`barthes_rhetoric_of_the_image_analysis_method_id`) REFERENCES `FIPOP`.`barthes_rhetoric_of_the_image` (`analysis_method_id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`genette_narrative_discourse` ADD CONSTRAINT `fk_genette_narrative_discourse_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`greimas_actantial_model` ADD CONSTRAINT `fk_greimas_actantial_model_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`greimas_actantial_model_has_actor` ADD CONSTRAINT `fk_greimas_actantial_model_has_actor_greimas_actantial_model1` FOREIGN KEY (`greimas_actantial_model_analysis_method_id`) REFERENCES `FIPOP`.`greimas_actantial_model` (`analysis_method_id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`greimas_actantial_model_has_concept` ADD CONSTRAINT `fk_greimas_actantial_model_has_concept_greimas_actantial_model1` FOREIGN KEY (`greimas_actantial_model_analysis_method_id`) REFERENCES `FIPOP`.`greimas_actantial_model` (`analysis_method_id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`linguistic_message` ADD CONSTRAINT `fk_linguistic_message_barthes_rhetoric_of_the_image1` FOREIGN KEY (`barthes_rhetoric_of_the_image_analysis_method_id`) REFERENCES `FIPOP`.`barthes_rhetoric_of_the_image` (`analysis_method_id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`lotman_renner_spatial_semantics` ADD CONSTRAINT `fk_lotman_renner_spatial_semantics_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`martinez_scheffel_unreliable_narration` ADD CONSTRAINT `fk_martinez_scheffel_unreliable_narration_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`sound_effect_descriptive` ADD CONSTRAINT `fk_sound_effect_descriptive_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`spatial_semantics_type_actor_person` ADD CONSTRAINT `fk_spatial_semantics_type_actor_person_lotman_renner_spatial_s1` FOREIGN KEY (`lotman_renner_spatial_semantics_analysis_method_id`) REFERENCES `FIPOP`.`lotman_renner_spatial_semantics` (`analysis_method_id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`spatial_semantics_type_space` ADD CONSTRAINT `fk_spatial_semantics_type_space_lotman_renner_spatial_semantics1` FOREIGN KEY (`lotman_renner_spatial_semantics_analysis_method_id`) REFERENCES `FIPOP`.`lotman_renner_spatial_semantics` (`analysis_method_id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`stanzel_narrative_situations` ADD CONSTRAINT `fk_stanzel_narrative_situations_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`van_sijll_cinematic_storytelling` ADD CONSTRAINT `fk_van_sijll_cinematic_storytelling_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`zelizer_beese_voice_of_the_visual` ADD CONSTRAINT `fk_zelizer_beese_voice_of_the_visual_analysis_method1` FOREIGN KEY (`analysis_method_id`) REFERENCES `FIPOP`.`analysis_method` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE `FIPOP`.`greimas_actantial_model_has_actor` DROP FOREIGN KEY `fk_greimas_actantial_model_has_actor_actor1`;
ALTER TABLE `FIPOP`.`greimas_actantial_model_has_actor` ADD CONSTRAINT `fk_greimas_actantial_model_has_actor_actor1` FOREIGN KEY (`actor_id`) REFERENCES `FIPOP`.`actor` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`greimas_actantial_model_has_actor` DROP FOREIGN KEY `fk_greimas_actantial_model_has_actor_actantial_model_facet_type1`;
ALTER TABLE `FIPOP`.`greimas_actantial_model_has_actor` ADD CONSTRAINT `fk_greimas_actantial_model_has_actor_actantial_model_facet_type1` FOREIGN KEY (`actantial_model_facet_type_id`) REFERENCES `FIPOP`.`actantial_model_facet_type` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`greimas_actantial_model_has_concept` DROP FOREIGN KEY `fk_greimas_actantial_model_has_concept_actantial_model_facet_t1`;
ALTER TABLE `FIPOP`.`greimas_actantial_model_has_concept` ADD CONSTRAINT `fk_greimas_actantial_model_has_concept_actantial_model_facet_t1` FOREIGN KEY (`actantial_model_facet_type_id`) REFERENCES `FIPOP`.`actantial_model_facet_type` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`ideology_has_ideologeme` DROP FOREIGN KEY `fk_ideology_has_ideologeme_ideology1`;
ALTER TABLE `FIPOP`.`ideology_has_ideologeme` ADD CONSTRAINT `fk_ideology_has_ideologeme_ideology1` FOREIGN KEY (`ideology_id`) REFERENCES `FIPOP`.`ideology` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`ideology_has_ideologeme` DROP FOREIGN KEY `fk_ideology_has_ideologeme_ideologeme1`;
ALTER TABLE `FIPOP`.`ideology_has_ideologeme` ADD CONSTRAINT `fk_ideology_has_ideologeme_ideologeme1` FOREIGN KEY (`ideologeme_id`) REFERENCES `FIPOP`.`ideologeme` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`lexia_has_connoted_image` DROP FOREIGN KEY `fk_lexia_has_connoted_image_lexia1`;
ALTER TABLE `FIPOP`.`lexia_has_connoted_image` ADD CONSTRAINT `fk_lexia_has_connoted_image_lexia1` FOREIGN KEY (`lexia_id`) REFERENCES `FIPOP`.`lexia` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`lexia_has_connoted_image` DROP FOREIGN KEY `fk_lexia_has_connoted_image_connoted_image1`;
ALTER TABLE `FIPOP`.`lexia_has_connoted_image` ADD CONSTRAINT `fk_lexia_has_connoted_image_connoted_image1` FOREIGN KEY (`connoted_image_id`) REFERENCES `FIPOP`.`connoted_image` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`lexia_has_denoted_image` DROP FOREIGN KEY `fk_lexia_has_denoted_image_lexia1`;
ALTER TABLE `FIPOP`.`lexia_has_denoted_image` ADD CONSTRAINT `fk_lexia_has_denoted_image_lexia1` FOREIGN KEY (`lexia_id`) REFERENCES `FIPOP`.`lexia` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`lexia_has_denoted_image` DROP FOREIGN KEY `fk_lexia_has_denoted_image_denoted_image1`;
ALTER TABLE `FIPOP`.`lexia_has_denoted_image` ADD CONSTRAINT `fk_lexia_has_denoted_image_denoted_image1` FOREIGN KEY (`denoted_image_id`) REFERENCES `FIPOP`.`denoted_image` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`lexia_has_linguistic_message` DROP FOREIGN KEY `fk_lexia_has_linguistic_message_lexia1`;
ALTER TABLE `FIPOP`.`lexia_has_linguistic_message` ADD CONSTRAINT `fk_lexia_has_linguistic_message_lexia1` FOREIGN KEY (`lexia_id`) REFERENCES `FIPOP`.`lexia` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`lexia_has_linguistic_message` DROP FOREIGN KEY `fk_lexia_has_linguistic_message_linguistic_message1`;
ALTER TABLE `FIPOP`.`lexia_has_linguistic_message` ADD CONSTRAINT `fk_lexia_has_linguistic_message_linguistic_message1` FOREIGN KEY (`linguistic_message_id`) REFERENCES `FIPOP`.`linguistic_message` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`religious_reference` DROP FOREIGN KEY `fk_religious_reference_medium_text1`;
ALTER TABLE `FIPOP`.`religious_reference` ADD CONSTRAINT `fk_religious_reference_medium_text1` FOREIGN KEY (`medium_text_medium_id`) REFERENCES `FIPOP`.`medium_text` (`medium_id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `FIPOP`.`van_sijll_cinematic_storytelling` DROP FOREIGN KEY `fk_van_sijll_cinematic_storytelling_cinematic_storytelling_con1`;
ALTER TABLE `FIPOP`.`van_sijll_cinematic_storytelling` ADD CONSTRAINT `fk_van_sijll_cinematic_storytelling_cinematic_storytelling_con1` FOREIGN KEY (`cinematic_storytelling_convention_id`) REFERENCES `FIPOP`.`cinematic_storytelling_convention` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;