name: timaat
services:
  db:
    image: mariadb:11.4
    ports:
      - "3306:3306"
    networks:
      - timaat-backend
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/database-root-password
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - database-root-password
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -u root --password=$(cat /run/secrets/database-root-password)"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
  webservice:
    image: nicokotlenga/nko_test_repo:latest
    pull_policy: always
    networks:
      - timaat-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD_FILE: /run/secrets/database-root-password
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    volumes:
      - file-storage:/var/lib/timaat/storage
    secrets:
      - database-root-password
    depends_on:
      db:
        condition: service_healthy
networks:
  timaat-backend:
    driver: bridge
    attachable: false
volumes:
  db-data:
  file-storage:
secrets:
  database-root-password:
    file: passwords/database-root-password.txt
